# Generated by Django 5.1.7 on 2025-04-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0002_rename_libro_videojuego_alter_videojuego_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='videojuegos/'),
        ),
    ]
