# Generated by Django 5.1.7 on 2025-04-17 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0003_videojuego_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='modulo.videojuego')),
            ],
        ),
    ]
