# Generated by Django 5.1.7 on 2025-04-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0004_videojuego_sinopsis_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='comentario',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
