# Generated by Django 5.1.7 on 2025-04-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0008_remove_comentario_rating_comentario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
