# Generated by Django 5.1.7 on 2025-04-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0009_remove_comentario_usuario_comentario_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='ISBN',
        ),
    ]
